name: YOLOwind
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - conda-forge
dependencies:
  - absl-py=1.3.0=py39haa95532_0
  - aiohttp=3.8.3=py39h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39haa95532_0
  - attrs=22.1.0=py39haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - bottleneck=1.3.5=py39h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.0.5=py39h59b6b97_0
  - cryptography=39.0.1=py39h21b164f_0
  - cuda-cccl=12.1.55=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.1.55=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - filelock=3.9.0=py39haa95532_0
  - flit-core=3.8.0=py39haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py39h2bbff1b_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hc60d5dd_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - importlib-metadata=6.0.0=py39haa95532_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=haa95532_3556
  - jinja2=3.1.2=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.19.4=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hf4acfee_0
  - libclang13=14.0.6=default_h8992b79_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py39haa95532_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib=3.7.1=py39haa95532_1
  - matplotlib-base=3.7.1=py39hf11a4ad_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - mpmath=1.2.1=py39haa95532_0
  - multidict=6.0.2=py39h2bbff1b_0
  - munkres=1.1.4=py_0
  - networkx=2.8.4=py39haa95532_1
  - numexpr=2.8.4=py39h5b0cc5e_0
  - numpy=1.23.5=py39h3b20f71_0
  - numpy-base=1.23.5=py39h4da318b_0
  - oauthlib=3.2.2=py39haa95532_0
  - onnx=1.13.0=py39h9724e47_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=23.0=py39haa95532_0
  - pandas=1.5.3=py39hf11a4ad_0
  - pcre=8.45=hd77b12b_0
  - pillow=9.4.0=py39hd77b12b_0
  - pip=23.0.1=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39haa95532_0
  - pyopenssl=23.0.0=py39haa95532_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.7=py39hd77b12b_0
  - pyqt5-sip=12.11.0=py39hd77b12b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.16=h6244533_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=2.0.0=py3.9_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_3
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py39haa95532_0
  - pyyaml=6.0=py39h2bbff1b_1
  - qt-main=5.15.2=he8e5bd7_8
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h3ad3cdb_4
  - requests=2.28.1=py39haa95532_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.10.1=py39h321e85e_0
  - seaborn=0.12.2=py39haa95532_0
  - setuptools=65.6.3=py39haa95532_0
  - sip=6.6.2=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h2bbff1b_0
  - sympy=1.11.1=py39haa95532_0
  - tensorboard=2.10.0=py39haa95532_0
  - tensorboard-data-server=0.6.1=py39haa95532_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py39h2bbff1b_0
  - tqdm=4.65.0=py39hd4e2768_0
  - typing-extensions=4.4.0=py39haa95532_0
  - typing_extensions=4.4.0=py39haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=2.2.3=py39haa95532_0
  - wheel=0.38.4=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py39h2bbff1b_0
  - zipp=3.11.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.4=hd43e919_0
  - pip:
      - docker-pycreds==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - onnx-simplifier==0.4.19
      - opencv-python==4.7.0.72
      - pathtools==0.1.2
      - protobuf==3.19.6
      - psutil==5.9.4
      - pygments==2.15.0
      - rich==13.3.3
      - sentry-sdk==1.19.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - thop==0.1.1-2209072238
      - torchaudio==2.0.0
      - torchvision==0.15.0
      - wandb==0.14.2
prefix: E:\anaconda\envs\YOLOwind
