wandb_version: 1

weights:
  desc: null
  value: ''
cfg:
  desc: null
  value: models/yolov5s.yaml
data:
  desc: null
  value: wind-data/wind.yaml
hyp:
  desc: null
  value:
    lr0: 0.001
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    pts: 0.1
    cls: 0.5
    cls_pw: 1.0
    obj: 1.0
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v:
    - 0.3
    - 1.2
    degrees: 180.0
    translate: 0.25
    scale:
    - 0.3
    - 1.6
    shear: 5.0
    perspective: 0.0003
    flipud: 0.0
    fliplr: 0.0
    mosaic: 0.4
    background_erase: 0.6
    mixup: 0.0
    copy_paste: 0.0
    bigBall: 0.1
    redPoint: 0.5
epochs:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 8
imgsz:
  desc: null
  value: 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: true
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: null
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: ''
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: true
sync_bn:
  desc: null
  value: false
workers:
  desc: null
  value: 1
project:
  desc: null
  value: runs/train
name:
  desc: null
  value: exp
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
patience:
  desc: null
  value: 100
freeze:
  desc: null
  value: 0
save_period:
  desc: null
  value: 100
local_rank:
  desc: null
  value: -1
negative_path:
  desc: null
  value:
  - D:/300-600/images/train
entity:
  desc: null
  value: null
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
save_dir:
  desc: null
  value: runs\train\exp4
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681198780.261161
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 3
      - 5
data_dict:
  desc: null
  value:
    path: E:/YOLOwind/wind-data
    train: E:\YOLOwind\wind-data\images\train
    val: E:\YOLOwind\wind-data\images\val
    nc: 6
    np: 5
    colors: 2
    tags: 3
    names:
    - BR
    - BU
    - BA
    - RR
    - RU
    - RA
    date: 2023/4/11
